# Generated by Django 4.2.4 on 2023-08-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referral", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="activate_invite_code",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="invite_code",
            field=models.CharField(default="000000", max_length=6),
        ),
    ]
