# Generated by Django 4.2.4 on 2023-08-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("referral", "0002_usermodel_activate_invite_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="user_activate_code",
            field=models.CharField(default="0000", max_length=4),
        ),
    ]
